import { RegionInfo } from "../types";

const EUROPEAN_COUNTRY_KEYS = [
  "EU_AX",
  "EU_AL",
  "EU_AD",
  "EU_AT",
  "EU_BY",
  "EU_BE",
  "EU_BA",
  "EU_BG",
  "EU_HR",
  "EU_CY",
  "EU_CZ",
  "EU_DK",
  "EU_EE",
  "EU_FO",
  "EU_FI",
  "EU_FR",
  "EU_DE",
  "EU_GI",
  "EU_GR",
  "EU_GG",
  "EU_HU",
  "EU_IS",
  "EU_IE",
  "EU_IM",
  "EU_IT",
  "EU_JE",
  "EU_XK",
  "EU_LV",
  "EU_LI",
  "EU_LT",
  "EU_LU",
  "EU_MK",
  "EU_MT",
  "EU_MD",
  "EU_MC",
  "EU_ME",
  "EU_NL",
  "EU_NO",
  "EU_PL",
  "EU_PT",
  "EU_RO",
  "EU_RU",
  "EU_SM",
  "EU_RS",
  "EU_SK",
  "EU_SI",
  "EU_ES",
  "EU_SJ",
  "EU_SE",
  "EU_CH",
  "EU_UA",
  "EU_GB",
  "EU_VA",
] as const;

export const EUROPEAN_REGION_INFO: Record<
  typeof EUROPEAN_COUNTRY_KEYS[number],
  RegionInfo
> = {
  EU_AX: {
    name: "Aland Islands",
    retailerCount: 450,
    polygons: [],
  },
  EU_AL: {
    name: "Albania",
    retailerCount: 450,
    polygons: [],
  },
  EU_AD: {
    name: "Andorra",
    retailerCount: 450,
    polygons: [],
  },
  EU_AT: {
    name: "Austria",
    retailerCount: 450,
    polygons: [],
  },
  EU_BY: {
    name: "Belarus",
    retailerCount: 450,
    polygons: [],
  },
  EU_BE: {
    name: "Belgium",
    retailerCount: 450,
    polygons: [],
  },
  EU_BA: {
    name: "Bosnia and Herzegovina",
    retailerCount: 450,
    polygons: [],
  },
  EU_BG: {
    name: "Bulgaria",
    retailerCount: 450,
    polygons: [],
  },
  EU_HR: {
    name: "Croatia",
    retailerCount: 450,
    polygons: [],
  },
  EU_CY: {
    name: "Cyprus",
    retailerCount: 450,
    polygons: [],
  },
  EU_CZ: {
    name: "Czechia",
    retailerCount: 450,
    polygons: [],
  },
  EU_DK: {
    name: "Denmark",
    retailerCount: 450,
    polygons: [],
  },
  EU_EE: {
    name: "Estonia",
    retailerCount: 450,
    polygons: [],
  },
  EU_FO: {
    name: "Faroe Islands",
    retailerCount: 450,
    polygons: [],
  },
  EU_FI: {
    name: "Finland",
    retailerCount: 450,
    polygons: [],
  },
  EU_FR: {
    name: "France",
    retailerCount: 450,
    polygons: [],
  },
  EU_DE: {
    name: "Germany",
    retailerCount: 450,
    polygons: [],
  },
  EU_GI: {
    name: "Gibraltar",
    retailerCount: 450,
    polygons: [],
  },
  EU_GR: {
    name: "Greece",
    retailerCount: 450,
    polygons: [],
  },
  EU_GG: {
    name: "Guernsey",
    retailerCount: 450,
    polygons: [],
  },
  EU_HU: {
    name: "Hungary",
    retailerCount: 450,
    polygons: [],
  },
  EU_IS: {
    name: "Iceland",
    retailerCount: 450,
    polygons: [],
  },
  EU_IE: {
    name: "Ireland",
    retailerCount: 450,
    polygons: [],
  },
  EU_IM: {
    name: "Isle of Man",
    retailerCount: 450,
    polygons: [],
  },
  EU_IT: {
    name: "Italy",
    retailerCount: 450,
    polygons: [],
  },
  EU_JE: {
    name: "Jersey",
    retailerCount: 450,
    polygons: [],
  },
  EU_XK: {
    name: "Kosovo",
    retailerCount: 450,
    polygons: [],
  },
  EU_LV: {
    name: "Latvia",
    retailerCount: 450,
    polygons: [],
  },
  EU_LI: {
    name: "Liechtenstein",
    retailerCount: 450,
    polygons: [],
  },
  EU_LT: {
    name: "Lithuania",
    retailerCount: 450,
    polygons: [],
  },
  EU_LU: {
    name: "Luxembourg",
    retailerCount: 450,
    polygons: [],
  },
  EU_MK: {
    name: "Macedonia",
    retailerCount: 450,
    polygons: [],
  },
  EU_MT: {
    name: "Malta",
    retailerCount: 450,
    polygons: [],
  },
  EU_MD: {
    name: "Moldova",
    retailerCount: 450,
    polygons: [],
  },
  EU_MC: {
    name: "Monaco",
    retailerCount: 450,
    polygons: [],
  },
  EU_ME: {
    name: "Montenegro",
    retailerCount: 450,
    polygons: [],
  },
  EU_NL: {
    name: "Netherlands",
    retailerCount: 450,
    polygons: [],
  },
  EU_NO: {
    name: "Norway",
    retailerCount: 450,
    polygons: [],
  },
  EU_PL: {
    name: "Poland",
    retailerCount: 450,
    polygons: [],
  },
  EU_PT: {
    name: "Portugal",
    retailerCount: 450,
    polygons: [],
  },
  EU_RO: {
    name: "Romania",
    retailerCount: 450,
    polygons: [],
  },
  EU_RU: {
    name: "Russia",
    retailerCount: 450,
    polygons: [],
  },
  EU_SM: {
    name: "San Marino",
    retailerCount: 450,
    polygons: [],
  },
  EU_RS: {
    name: "Serbia",
    retailerCount: 450,
    polygons: [],
  },
  EU_SK: {
    name: "Slovakia",
    retailerCount: 450,
    polygons: [],
  },
  EU_SI: {
    name: "Slovenia",
    retailerCount: 450,
    polygons: [],
  },
  EU_ES: {
    name: "Spain",
    retailerCount: 450,
    polygons: [],
  },
  EU_SJ: {
    name: "Svalbard and Jan Mayen",
    retailerCount: 450,
    polygons: [],
  },
  EU_SE: {
    name: "Sweden",
    retailerCount: 450,
    polygons: [],
  },
  EU_CH: {
    name: "Switzerland",
    retailerCount: 450,
    polygons: [],
  },
  EU_UA: {
    name: "Ukraine",
    retailerCount: 450,
    polygons: [],
  },
  EU_GB: {
    name: "United Kingdom",
    retailerCount: 450,
    polygons: [],
  },
  EU_VA: {
    name: "Vatican City",
    retailerCount: 450,
    polygons: [],
  },
};
