export const EUR_COUNTRY_CODES = [
  "ALB",
  "AND",
  "AUT",
  "BLR",
  "BEL",
  "BIH",
  "BGR",
  "HRV",
  "CYP",
  "CZE",
  "DNK",
  "EST",
  "FRO",
  "FIN",
  "FRA",
  "DEU",
  "GIB",
  "GRC",
  "HUN",
  "ISL",
  "IRL",
  "IMN",
  "ITA",
  "XKX",
  "LVA",
  "LIE",
  "LTU",
  "LUX",
  "MKD",
  "MLT",
  "MDA",
  "MCO",
  "MNE",
  "NLD",
  "NOR",
  "POL",
  "PRT",
  "ROU",
  "SMR",
  "SRB",
  "SVK",
  "SVN",
  "ESP",
  "SWE",
  "CHE",
  "UKR",
  "GBR",
  "VAT",
  "RSB",
];

export const OCEANIA_COUNTRY_CODES = ["AUS", "NZL"];

export const CANADIAN_PROVINCE_NAME_CODE_MAP = {
  Alberta: "CAN_AB",
  "British Columbia": "CAN_BC",
  Manitoba: "CAN_MB",
  "New Brunswick": "CAN_NB",
  "Newfoundland and Labrador": "CAN_NL",
  "Northwest Territories": "CAN_NT",
  "Nova Scotia": "CAN_NS",
  Nunavut: "CAN_NU",
  Ontario: "CAN_ON",
  "Prince Edward Island": "CAN_PE",
  Quebec: "CAN_QC",
  Saskatchewan: "CAN_SK",
  Yukon: "CAN_YT",
};

export const US_STATE_NAME_CODE_MAP = {
  Alabama: "USA_AL",
  Alaska: "USA_AK",
  Arizona: "USA_AZ",
  Arkansas: "USA_AR",
  California: "USA_CA",
  Colorado: "USA_CO",
  Connecticut: "USA_CT",
  Delaware: "USA_DE",
  Florida: "USA_FL",
  Georgia: "USA_GA",
  Hawaii: "USA_HI",
  Idaho: "USA_ID",
  Illinois: "USA_IL",
  Indiana: "USA_IN",
  Iowa: "USA_IA",
  Kansas: "USA_KS",
  Kentucky: "USA_KY",
  Louisiana: "USA_LA",
  Maine: "USA_ME",
  Maryland: "USA_MD",
  Massachusetts: "USA_MA",
  Michigan: "USA_MI",
  Minnesota: "USA_MN",
  Mississippi: "USA_MS",
  Missouri: "USA_MO",
  Montana: "USA_MT",
  Nebraska: "USA_NE",
  Nevada: "USA_NV",
  "New Hampshire": "USA_NH",
  "New Jersey": "USA_NJ",
  "New Mexico": "USA_NM",
  "New York": "USA_NY",
  "North Carolina": "USA_NC",
  "North Dakota": "USA_ND",
  Ohio: "USA_OH",
  Oklahoma: "USA_OK",
  Oregon: "USA_OR",
  Pennsylvania: "USA_PA",
  Rhode: "USA_RI",
  "South Carolina": "USA_SC",
  "South Dakota": "USA_SD",
  Tennessee: "USA_TN",
  Texas: "USA_TX",
  Utah: "USA_UT",
  Vermont: "USA_VT",
  Virginia: "USA_VA",
  Washington: "USA_WA",
  "West Virginia": "USA_WV",
  Wisconsin: "USA_WI",
  Wyoming: "USA_WY",
};
