import Head from "next/head";
import styled from "styled-components";

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <h1>Hello World</h1>
      </Container>
    </>
  );
};

const Container = styled.div`
  width: 100%;
  border: 1px solid red;
`;

export default Home;
